### ISSUE TITLE
@nestjs/terminus does the same :)

### ISSUE THREAD

**Issue by BrunnerLivio** [Wi-Q/nestjs-health-check#1]
Hi, just saw on my Github feed this repository got created.

Just wanted to remind you if you did not know yet; NestJS supports health checks already with [@nestjs/terminus](https://github.com/nestjs/terminus). Not that you waste your time. 

But if you knew and want a better option than our implementation - go ahead :)

**Comment by bashleigh** [comment]
oooooo that is handy :D thanks! I was just creating a package for a controller as I've got multiple projects with the same controller. I'll give Terminus a go :) Thanks!
